Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -17,10 +17,10 @@ jobs:
         run: |
           echo "hello"
           export MY_TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=vjtest" | jq -r '.value')
-          echo $MY_TOKEN
-          export MONDOO_CONFIG_BASE64=$(curl --request POST --url 'https://24b5-2601-283-5001-ef67-51c8-9d78-f36a-7b26.ngrok-free.app/SecureTokenService/ExchangeExternalToken' --header 'content-type: application/json' --data '{"audience": "//captain.api.mondoo.app/spaces/test-infallible-taussig-796596","issuer_uri": "https://token.actions.githubusercontent.com","jwt_token": "'"${MY_TOKEN}"'"}' | jq -r '.base64_credential')
+          # echo $MY_TOKEN
+          # export MONDOO_CONFIG_BASE64=$(curl --request POST --url 'https://24b5-2601-283-5001-ef67-51c8-9d78-f36a-7b26.ngrok-free.app/SecureTokenService/ExchangeExternalToken' --header 'content-type: application/json' --data '{"audience": "//captain.api.mondoo.app/spaces/test-infallible-taussig-796596","issuer_uri": "https://token.actions.githubusercontent.com","jwt_token": "'"${MY_TOKEN}"'"}' | jq -r '.base64_credential')
           cnspec status
-          if [ $(echo $?) != 0 ]; then echo "failed to reach mondoo" exit 1; fi
+          # if [ $(echo $?) != 0 ]; then echo "failed to reach mondoo" exit 1; fi
           export MONDOO_CONFIG_BASE64=eyJtcm4iOiIvL2FnZW50cy5hcGkubW9uZG9vLmFwcC9zcGFjZXMvZnVubnktcG9pdHJhcy0xNjgzOTUvc2VydmljZWFjY291bnRzLzJ0ZHJGM29TNzQ3WFNvdDN1MXZjbDVabFdrTCIsImNlcnRpZmljYXRlIjoiLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlDY2pDQ0FmbWdBd0lCQWdJUU9kZng2clZpU2d3Ri8vR3VpejM4eHpBS0JnZ3Foa2pPUFFRREF6QS9NVDB3XG5Pd1lEVlFRS0V6UXZMMk5oY0hSaGFXNHVZWEJwTG0xdmJtUnZieTVoY0hBdmMzQmhZMlZ6TDJaMWJtNTVMWEJ2XG5hWFJ5WVhNdE1UWTRNemsxTUNBWERUSTFNREl5TnpJeE5EUTBOVm9ZRHprNU9Ua3hNak14TWpNMU9UVTVXakEvXG5NVDB3T3dZRFZRUUtFelF2TDJOaGNIUmhhVzR1WVhCcExtMXZibVJ2Ynk1aGNIQXZjM0JoWTJWekwyWjFibTU1XG5MWEJ2YVhSeVlYTXRNVFk0TXprMU1IWXdFQVlIS29aSXpqMENBUVlGSzRFRUFDSURZZ0FFTFJyU2JzZjFCYXd0XG5aZVMxMy9iYnVuTkNtK1lpOUV1QzcwZXZrYXowdWhHK09zcmRxOWdadTE2LzFNNWlYQU84dUhnSHJFRGxLR1FkXG5MZGtXMnRDeXBIbllVc2tUaEVtaWUrRGtxNDdwZWlYUXg5bDBNMElpWUY2d05MSUh5NUtubzRHM01JRzBNQTRHXG5BMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQU1CZ05WSFJNQkFmOEVBakFBXG5NR29HQTFVZEVRUmpNR0dDWHk4dllXZGxiblJ6TG1Gd2FTNXRiMjVrYjI4dVlYQndMM053WVdObGN5OW1kVzV1XG5lUzF3YjJsMGNtRnpMVEUyT0RNNU5TOXpaWEoyYVdObFlXTmpiM1Z1ZEhNdk1uUmtja1l6YjFNM05EZFlVMjkwXG5NM1V4ZG1Oc05WcHNWMnRNTUJNR0ExVWRKZ1FNREFwMlpYSnphVzl1T25ZeU1Bb0dDQ3FHU000OUJBTURBMmNBXG5NR1FDTUdXVWFTak1lV0hYMjVOcDljUTdGRmpSZFhOa2dVNFlqVnd3UzFXQkxqeStqV3hvYjN2QXdUdU4wbzZmXG5lOWtyS3dJd0tkVEt4V2VaTVVvb1kxdTdwdUtreEZuZkhXMDA3MUdFeGtxUE1XKzhDcWJsQU9TVkdocWhPdHNyXG5MUUtxTTVST1xuLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLVxuIiwicHJpdmF0ZV9rZXkiOiItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JRzJBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQklHZU1JR2JBZ0VCQkRBZVNEU2toYUdVTWNqWTgyVC9cbnBMbjJiQSsrZGl1RGd0dDZhUnViQnN4WkNmRFN3UHkxOWt3WGZYQlg2RVZWRjV5aFpBTmlBQVF0R3RKdXgvVUZcbnJDMWw1TFhmOXR1NmMwS2I1aUwwUzRMdlI2K1JyUFM2RWI0Nnl0MnIyQm03WHIvVXptSmNBN3k0ZUFlc1FPVW9cblpCMHQyUmJhMExLa2VkaFN5Uk9FU2FKNzRPU3JqdWw2SmRESDJYUXpRaUpnWHJBMHNnZkxrcWM9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLCJzY29wZV9tcm4iOiIvL2NhcHRhaW4uYXBpLm1vbmRvby5hcHAvc3BhY2VzL2Z1bm55LXBvaXRyYXMtMTY4Mzk1IiwiYXBpX2VuZHBvaW50IjoiaHR0cHM6Ly9hcGkuZWRnZS5tb25kb28uY29tIiwic3BhY2VfbXJuIjoiLy9jYXB0YWluLmFwaS5tb25kb28uYXBwL3NwYWNlcy9mdW5ueS1wb2l0cmFzLTE2ODM5NSIsInR5cGVuYW1lIjoiU2VydmljZUFjY291bnRDcmVkZW50aWFsIn0=
 
           cnspec scan
